### ISSUE TITLE
Missing resource for instal BEAR

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/bear#3]
The provided link in the README to [VISR](https://github.com/s3a-spatialaudio/VISR)
only provides version 0.12.2 instead of the required 0.13.0.

**Comment by tomjnixon** [comment]
Hi,

Yes, unfortunately i've had a bit of trouble getting them to release the next version -- it's available here for now https://github.com/ebu/bear/releases/download/v0.0.1-pre/visr-0.13.0-pre-5e13f020.zip

The install process is unfortunately quite involved. If you just want to evaluate this I could provide a docker container that's much easier to get started with -- would that be helpful?

**Comment by WernerBleisteiner** [comment]
Hi Tom,
thanks. Yes, I'd appreciate to give it a try with a docker first - if this shouldn't work, I can always try the classic way...;)
w

**Comment by tomjnixon** [comment]
Hi, sorry for the delay. There's some instructions for this in the readme now.
